### ISSUE TITLE
chooseSaveDirectory is not a function

### ISSUE THREAD

**Issue by fullee** [trzsz/trzsz.js#4]
```javascript
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/trzsz/svr/send.py", line 73, in main
    action = recv_action()
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 318, in recv_action
    return recv_json('ACT')
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 307, in recv_json
    dic = recv_string(typ, may_has_junk)
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 233, in recv_string
    return decode_buffer(recv_check(typ, may_has_junk)).decode('utf8')
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 213, in recv_check
    raise TrzszError(buf, typ)
trzsz.libs.utils.TrzszError: TypeError: this.chooseSaveDirectory is not a function
    at t2.<anonymous> (http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:2655:29)
    at http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:109:21
    at Object.next (http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:118:8)
    at http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:55:38
    at new Promise (<anonymous>)
    at e (http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:34:10)
    at t2.handleTrzszDownloadFiles (http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:2648:12)
    at t2.<anonymous> (http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:2621:131)
    at http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:109:21
    at Object.next (http://localhost:3000/node_modules/.vite/deps/trzsz.js?v=a7c740da:118:8)
```

**Comment by lonnywong** [comment]
It's running with Node.js environment. You need to implement the two functions.

```js
const trzszFilter = new TrzszFilter({
  // call on the user runs trz ( upload files ) on the server and no error on require('fs').
  chooseSendFiles: async () => {
    // return `undefined` if the user cancels.
    // return an array of file paths choosed by the user.
    return ["/path/to/file1", "/path/to/file2"];
  },
  // call on the user runs tsz ( download files ) on the server and no error on require('fs').
  chooseSaveDirectory: async () => {
    // return `undefined` if the user cancels.
    // return a directory path choosed by the user.
    return "/path/to/directory";
  },
});
```

**Comment by fullee** [comment]
i used xterm.js join trzsz by TrzszAddon @lonnywong 
![image](https://user-images.githubusercontent.com/11188837/167763952-b6d3c37f-a83c-4960-8c07-0316ae933438.png)

**Comment by lonnywong** [comment]
> i used xterm.js join trzsz by TrzszAddon 

You can implement `chooseSendFiles` and `chooseSaveDirectory` too.

```js
const trzszAddon = new TrzszAddon(webSocket, {
  // call on the user runs trz ( upload files ) on the server and no error on require('fs').
  chooseSendFiles: async () => {
    // return `undefined` if the user cancels.
    // return an array of file paths choosed by the user.
    return ["/path/to/file1", "/path/to/file2"];
  },
  // call on the user runs tsz ( download files ) on the server and no error on require('fs').
  chooseSaveDirectory: async () => {
    // return `undefined` if the user cancels.
    // return a directory path choosed by the user.
    return "/path/to/directory";
  },
});
```
